akretion/roulier

- roulier/carriers/laposte/laposte.py
- roulier/carriers/laposte/laposte_decoder.py
- roulier/carriers/laposte/laposte_encoder.py
- roulier/carriers/laposte/laposte_transport.py
[IMP] refactor the response handler to be able to split the label and
eventually the CN23 returned by the Colissimo webservice
> Manage labels and CN23

- roulier/api.py
- roulier/carriers/dummy/dummy_api.py
- roulier/carriers/dummy/dummy_encoder.py
- roulier/carriers/dummy/templates/dummy_generateLabel.zpl
- roulier/carriers/laposte/__init__.py
- roulier/carriers/laposte/laposte.py
- roulier/carriers/laposte/laposte_api.py
- roulier/carriers/laposte/laposte_encoder.py
- roulier/carriers/laposte/laposte_transport.py
- roulier/carriers/laposte/templates/laposte_address.xml
- roulier/carriers/laposte/templates/laposte_generateLabelRequest.xml
- roulier/carriers/laposte/templates/laposte_getProductInter.xml
- roulier/carriers/laposte/templates/laposte_outputFormat.xml
- roulier/carriers/laposte/templates/laposte_parcel.xml
- roulier/carriers/laposte/templates/laposte_service.xml
- setup.py
Refactoring for api definition and validation using http://docs.python-cerberus.org/en/stable/usage.html
> use cerberus for data validation

- roulier/carriers/geodis/geodis_transport.py
> fix  Geodis Response error #16

- roulier/roulier.py
In order to know which carriers are available instead of looking through module's file structure
> Add get_carriers()

- roulier/carriers/dummy/dummy.py
- roulier/carriers/dummy/dummy_encoder.py
- roulier/carriers/laposte/laposte.py
- roulier/carriers/laposte/laposte_encoder.py
- roulier/roulier.py
fixes  explicite relative import #31
> use dot notation for imports

- roulier/carriers/laposte/laposte.py
- roulier/carriers/laposte/laposte_transport.py
Reverts akretion/roulier#26
because it doesn't work well when you have a response from the webservice
> Revert "Feat/refact err handl"

- roulier/carriers/laposte/laposte_api.py
- roulier/carriers/laposte/laposte_transport.py
> [FIX] pep8

- roulier/carriers/laposte/laposte_api.py
- roulier/carriers/laposte/templates/laposte_parcel.xml
+ clarification of expected types
> fix type issue on ftd

- roulier/carriers/laposte/laposte_transport.py
Force charset to utf-8 for laposte requests
> Fix accent issues with laposte

- roulier/carriers/geodis/geodis_encoder.py
- roulier/carriers/laposte/laposte_encoder.py
Activate jinja2.ext.autoescape
> Fix xml escaping in geodis and laposte

- roulier/carriers/laposte/laposte_api.py
- roulier/carriers/laposte/templates/laposte_generateLabelRequest.xml
for the moment : 
reference1 = reference client
reference2 = reference destinataire
previously it was hard coded
> Add reference in laposte

- roulier/carriers/laposte/laposte_transport.py
elapsed is not available in some requests versions
> Remove laposte

- roulier/carriers/laposte/laposte_api.py
Street 1 : mandatory -> ligne2
Street 2 : optional -> ligne1
> Revert street1/2

- roulier/carriers/trs/templates/trs_generateLabel.zpl
Reduce size of comments
Add reference1
fix zipcode
> Use Text block for address

- roulier/carriers/laposte/laposte_api.py
> [FIX] wrong change of street fields

- CHANGELOG.md
- roulier/carriers/dpd/dpd_api.py
- roulier/carriers/dpd/dpd_encoder.py
street2 is now appened to street1
company is now appened to name
> Fix addresses bug for DPD

- roulier/carriers/geodis/geodis_encoder_edi.py
> Fix Geodis EDI main name if no company

- README.md
- roulier.py
- roulier/api.py
- roulier/carriers/dpd/dpd_api.py
- roulier/carriers/dummy/dummy_api.py
- roulier/carriers/geodis/geodis_api_edi.py
- roulier/carriers/geodis/geodis_api_find_localite_ws.py
- roulier/carriers/geodis/geodis_api_ws.py
- roulier/carriers/laposte/laposte_api.py
- setup.py
* Remove description key from schema.
It was a hacky and not supported by cerberus > 1.1
* Remove csv lib not used anymore
> REMove description key, upd dep

- roulier/carriers/dpd_fr_soap/api.py
- roulier/carriers/dpd_fr_soap/tests/test_dpd.py
DPD was not usable with `Predict`. Test added.
> Fix dpd fr soap predict

- roulier/carriers/chronopost_fr/encoder.py
- roulier/carriers/chronopost_fr/transport.py
- roulier/carriers/dpd_fr_soap/encoder.py
- roulier/carriers/dpd_fr_soap/transport.py
- roulier/carriers/geodis/geodis_encoder_ws.py
- roulier/carriers/geodis/geodis_transport_ws.py
- roulier/carriers/laposte_fr/encoder.py
- roulier/carriers/laposte_fr/transport.py
> fix jinja2

- roulier/api.py
- roulier/carriers/dpd/dpd_encoder.py
- roulier/carriers/dpd/templates/dpd_addressInfo.xml
- roulier/carriers/dpd/templates/dpd_createShipmentWithLabels.xml
add field delivery_instruction into api address
> Delivery instruction

- roulier/carriers/geodis_fr/edi/api.py
- roulier/carriers/geodis_fr/edi/encoder.py
It may be important for shipments in foreign countries
> [IMP] Geodis : add possibility to add the volume in the EDI file

- roulier/carriers/mondialrelay/encoder.py
- roulier/carriers/mondialrelay/transport.py
fix compat issue with jinja2 with_ ext
This is not necessary anymore since it has been moved into the core of jinja2
> fix jinja with_ extension
